/**
 * Shared data model for the question-paper / answer-sheet pipeline.
 *
 * Pipeline: Question Extraction -> Answer Extraction -> Answer Mapping -> Grading/Feedback.
 * Each stage is a separate API call so the UI can show per-stage progress.
 */

/** A single rasterized page of an uploaded document (PDF page or standalone image). */
export interface SourcePage {
  pageIndex: number; // 0-based, order preserved from the original file
  dataUrl: string; // "data:image/jpeg;base64,...", rasterized client-side
  width: number;
  height: number;
}

/**
 * A rectangular region on one page, normalized to [0, 1000] on both axes
 * (matches Gemini's documented bounding-box convention), independent of the
 * page's actual pixel dimensions.
 */
export interface NormalizedBox {
  page: number; // index into the relevant SourcePage[] array
  yMin: number;
  xMin: number;
  yMax: number;
  xMax: number;
}

/**
 * One visual line of text with a box that was *measured* (from a PDF text layer
 * or an OCR engine), not generated by a model. The `id` is what the model is
 * asked to select by, so it never emits a coordinate itself.
 */
export interface IndexedLine {
  id: number;
  text: string;
  box: NormalizedBox;
}

export interface LineIndex {
  lines: IndexedLine[];
  pageCount: number;
}

/**
 * A question described by which measured lines it occupies. This is what the
 * model returns on the text-layer path; the caller turns `lineIds` into real
 * geometry, so no coordinate ever originates from the model.
 */
export interface QuestionSelection {
  number: string;
  parentNumber: string | null;
  text: string;
  lineIds: number[];
}

/**
 * An answer described by which measured lines it occupies. The transcript is
 * the model's own reading of the image (better than OCR); the location comes
 * from line IDs, so the caller derives exact geometry.
 */
export interface AnswerSelection {
  transcript: string;
  declaredLabel: string | null;
  lineIds: number[];
}

export interface Question {
  id: string;
  /** Printed numbering exactly as it appears, e.g. "11", "11(a)". */
  number: string;
  /** Parent number for a labelled sub-part, e.g. "11" for question "11(a)". */
  parentNumber: string | null;
  text: string;
  /** Null when the model returned an unusable box for this question. */
  box: NormalizedBox | null;
}

export interface AnswerBlock {
  id: string;
  /** Best-effort transcription of the handwriting. */
  transcript: string;
  /** The label the student wrote next to the answer, if legible (e.g. "Q11 (a)"). */
  declaredLabel: string | null;
  /** One or more regions — an answer may span multiple pages. */
  boxes: NormalizedBox[];
}

export type MappingStatus =
  | "answered" // matched 1:1 to a question
  | "unanswered" // question has no matching answer block
  | "unmatched_answer"; // answer block doesn't correspond to any known question

export interface Mapping {
  questionId: string | null;
  answerId: string | null;
  status: MappingStatus;
  confidence: number; // 0-1
  /** Short rationale from the model, useful for debugging + surfacing low-confidence matches. */
  reasoning: string;
}

export type Verdict = "correct" | "partially_correct" | "incorrect" | "ungraded";

export interface GradingResult {
  questionId: string;
  verdict: Verdict;
  score: number;
  maxScore: number;
  feedback: string;
}

export interface GradingSummary {
  totalScore: number;
  maxScore: number;
  overallFeedback: string;
  results: GradingResult[];
}

export type PipelineStage =
  | "idle"
  | "uploading"
  // The two extraction branches run concurrently, so they share one stage.
  | "extracting"
  | "mapping"
  | "grading"
  | "done"
  | "error";

export interface ExamSession {
  id: string;
  createdAt: number;
  stage: PipelineStage;
  error: string | null;
  /**
   * "measured" when question boxes came from a PDF text layer, "estimated"
   * when a vision model produced them. Worth surfacing: it's the difference
   * between exact geometry and a model's best guess.
   */
  questionGeometry: "measured" | "estimated";
  /** "measured" when answer boxes came from OCR word polygons rather than a model's estimate. */
  answerGeometry: "measured" | "estimated";
  questionPaperPages: SourcePage[];
  answerSheetPages: SourcePage[];
  questions: Question[];
  answers: AnswerBlock[];
  mappings: Mapping[];
  grading: GradingSummary | null;
}
